version: '3.8'
services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./build/es
      dockerfile: Dockerfile
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
  kibana:
    container_name: kibana
    build:
      context: ./build/kb
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_HOSTS=http://192.168.178.94:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
      - enterpriseSearch.host:'http://192.168.178.94:3002'
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always
networks:
  default:
    external:
      name: development
volumes:
  elasticsearch-data:




