version: '3.8'
services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./build/es
      dockerfile: Dockerfile
      args:
        VERSION: 7.17.9

    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
      - path.repo=/usr/share/elasticsearch/backup
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./backups:/usr/share/elasticsearch/backup
    ports:
      - 9200:9200
    restart: always
  kibana:
    container_name: kibana
    build:
      context: ./build/kb
      dockerfile: Dockerfile
      args:
        VERSION: 7.17.9
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always
networks:
  default:
    external:
      name: development
volumes:
  elasticsearch-data:




