version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: dev_elasticsearch
    environment:
      - node.name=elasticsearch
      - network.host=0.0.0.0
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
  kibana:
    container_name: dev_kibana
    image: docker.elastic.co/kibana/kibana:7.16.2
    environment:
      - ELASTICSEARCH_HOSTS=http://192.168.178.94:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
      - enterpriseSearch.host:'http://192.168.178.94:3002'
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always
networks:
  default:
    external:
      name: development
volumes:
  elasticsearch-data:




